### ISSUE TITLE
使用 client.metrics()报错。

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/trader-client#15]
* zillionare-trader-client version: zillionare-trader-client 0.3.10
* Python version: Python 3.8
* Operating System: Win 10

### Description
account: johnny_event_bk3_v18-4ba0

账户评估指标 failed: 499, The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "C:/Users/wx/PycharmProjects/stock_program/zillionare/4_回测并整理交易数据.py", line 250, in <module>
    metrics = client.metrics()
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\client.py", line 616, in metrics
    return get(url, headers=self.headers, params=params)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 85, in get
    result = process_response_result(rsp, action)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\transport.py", line 63, in process_response_result
    raise TradeError(rsp.status_code, rsp.text)
traderclient.errors.TradeError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all(): (499, 'The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()')

### What I Did
有时报错有时正常。

**Comment by zillionare** [comment]
transfer to zillionare/backtesting#17 and close this one
