### ISSUE TITLE
使用 client.sell() 报错，

### ISSUE THREAD

**Issue by Johnny-168** [zillionare/trader-client#8]
* zillionare-trader-client version:  zillionare-trader-client   0.3.9
* Python version: Python 3.8
* Operating System: Win 10

### Description
卖出{'security': '600273.XSHG', 'price': 10.15, 'volume': 4400}时，报错。

Traceback (most recent call last):
  File "C:/Users/wx/PycharmProjects/stock_program/zillionare/交易/一键下单.py", line 41, in <module>
    sell_info = client.sell(**sell_dict)
  File "C:\Users\wx\anaconda3\envs\stock_quant\lib\site-packages\traderclient\client.py", line 442, in sell
    rec["time"] = arrow.get(rec["time"]).naive
TypeError: string indices must be integers

**Comment by zillionare** [comment]
在回测模式下，卖出时间使用"time"字段来标识（实盘模式下为created_at/updated_at)。当切换为实盘时，代码少了一个判断，从而执行了回测模式下的解析代码，导致出错。
